### ISSUE TITLE
0.7.5 not working on ubuntu 14.04

### ISSUE THREAD

**Issue by freezeeedos** [syncthing/syncthing-gtk#197]
Hello,

I'm getting this error: 

`lib/python2.7/dist-packages/syncthing_gtk/__init__.py", line 16, in <module>
    from infobox			import InfoBox
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 8, in <module>
    from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg
ImportError: cannot import name Rsvg`

Is syncthing-gtk not supported on 14.04 anymore ?

**Comment by kozec** [comment]
Not exactly, but Ubuntu has stupid obsession with splitting libraries into _really_ small parts.

I will not have 14.04 on hand until evening, but you can try if there is any package with `rsvg` and, optionaly, `gobject` or `gobject-introspection` in name.

**Comment by rkfg** [comment]
I'm on Debian Stretch but today have had this exact issue. I reinstalled syncthing-gtk from the webupd8 repo and it installed `gir1.2-rsvg-2.0` package alongside. Then it all started working.

**Comment by kozec** [comment]
> I reinstalled syncthing-gtk from the webupd8 repo and it installed gir1.2-rsvg-2.0 package alongside. Then it all started working.

Ok, thanks. I added it to readme.

@hotice, would it be possible to add `gir1.2-rsvg-2.0` as dependency to Ubuntu package as well?

**Comment by rkfg** [comment]
It seems it's already added but for some reason was not installed in the first place. Maybe I updated the package in the wrong time?

**Comment by hotice** [comment]
@kozec I added it this morning.

**Comment by kozec** [comment]
> I added it this morning.

Great. Thanks :)
