### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#391]
Running on Windows 10 and installed using Chocolatey.

![2017-08-20 18_51_09-cx_freeze_ python error in main script](https://user-images.githubusercontent.com/931642/29500191-e7309a6c-860d-11e7-957f-318c83ab9a22.png)

**Comment by kozec** [comment]
Does same thing happens when you install without Chocolatey?

(also, sorry, but I have no idea what's written after "DLL load failed:" :)

**Comment by robsonsobral** [comment]
I gonna test after I get back home, @kozec .

After DLL load failed is written "It wasn't possible to find the specified module".

Thank you for your patience.

**Comment by tonirug** [comment]
Hi,
same problem here with standard install. Same problem also after downgrading from v0.9.2.5 to v0.9.2.4.
OS is Windows 10 with all updates installed.
Best

**Comment by kozec** [comment]
So, sounds like Windows 10 is missing some libs normal Windows has. This gonna be fun :(

**Comment by kozec** [comment]
> The problem happens only when syncthing-gtk is automatically launched at windows startup.
> No problem when launching it manually.

Ok, now this is important part. That's same as #385, issue that I still have no idea how can be even possible. @robsonsobral is it same on your side?

**Comment by robsonsobral** [comment]
I couldn't reinstall yet, I'm sorry, but, as happened with @tonirug , the error only occurs when launching with windows startup.

**Comment by acolomb** [comment]
I can confirm this happens on my Windows 7 machine at work, also only during windows startup. Syncthing-Gtk 0.9.2.5 from Chocolatey.

**Comment by kozec** [comment]
Can anyone of you confirm if registry value `Software\\SyncthingGTK\\InstallPath` points to correct directory on your side?

**Comment by acolomb** [comment]
Yes it does, but only exists under `HKEY_CURRENT_USER`, not under `HKEY_LOCAL_MACHINE`. Could it be that the former is not yet initialized completely during login?

**Comment by tonirug** [comment]
In W10 appears under Computer\HKEY_CURRENT_USER\Software\SyncthingGTK\InstallPath and the path is correct

**Comment by koldKat** [comment]
I have the exact same issue. On W7 and W10 machines. Automatic start fails. Manual works just fine.

**Comment by masgo** [comment]
Here is the English version of the error.

I am using Windows 10 Version 1703. 

Maybe it is already obvious, but there is no `C:\Python27` folder on my machine.

![syncthing-gtk](https://user-images.githubusercontent.com/1336992/30350331-8bc7089e-9816-11e7-8174-75d7623bc2cf.png)

**Comment by yaomtc** [comment]
Having the same issue, here's the text version of the error: 
```
Traceback (most recent call last):
 File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run 
 File "scripts/syncthing-gtk-exe.py", line 3, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by kozec** [comment]
Soo... I probably got it. Can anyone of you on Win10 try this build?

[SyncthingGTK-v0.9.2.5-2-g8864664-win32-full-installer.zip](https://github.com/syncthing/syncthing-gtk/files/1308172/SyncthingGTK-v0.9.2.5-2-g8864664-win32-full-installer.zip)

**Comment by robsonsobral** [comment]
It worked, @kozec !

**Comment by seiferflo** [comment]
Thanks @kozec, it's working with this new build !

**Comment by hugalafutro** [comment]
Thanks for the update it now works as expected when autostarting.

**Comment by yaomtc** [comment]
It also works again for me. Must be fixed now. Thanks a lot!

**Comment by kozec** [comment]
Thanks for all confirmation, this is now fixed in latest release.

**Comment by acolomb** [comment]
After upgrading to v0.9.2.7 from Chocolatey, this error still occurred for me at system boot. Even starting manually afterwards did not work: `ImportError: cannot import name Configuration`. Starting with `syncthing-gtk-console.exe` from a terminal kind of worked, but the connection to the daemon could not be established, although it was definitely reachable from a browser.

All these troubles went away after an uninstall - install cycle with Chocolatey. Hope this helps anybody still having similar troubles.
